USE master;
GO

CREATE DATABASE [$(MSSQL_DB)];
GO

USE $(MSSQL_DB);
GO

CREATE LOGIN [$(MSSQL_USER)] WITH PASSWORD='$(MSSQL_PASSWORD)', DEFAULT_DATABASE=[$(MSSQL_DB)], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO

CREATE USER [$(MSSQL_USER)] FOR LOGIN $(MSSQL_USER);
GO

ALTER SERVER ROLE [dbcreator] ADD MEMBER $(MSSQL_USER);
GO

EXEC sp_addrolemember 'db_owner', '$(MSSQL_USER)';
GO